table:
  name: jobs
  schema: public
object_relationships:
  - name: company
    using:
      foreign_key_constraint_on: company_id
  - name: jobType
    using:
      manual_configuration:
        column_mapping:
          type: type_name
        insertion_order: null
        remote_table:
          name: job_types
          schema: public
  - name: locationType
    using:
      foreign_key_constraint_on: location
array_relationships:
  - name: applications
    using:
      foreign_key_constraint_on:
        column: job_id
        table:
          name: applications
          schema: public
insert_permissions:
  - role: employer
    permission:
      check:
        company_id:
          _eq: X-Hasura-User-Id
      columns:
        - description
        - location
        - title
        - type
select_permissions:
  - role: anonymous
    permission:
      columns:
        - created_at
        - description
        - id
        - location
        - title
        - type
      filter:
        is_active:
          _eq: true
  - role: employer
    permission:
      columns:
        - company_id
        - created_at
        - deleted_at
        - description
        - id
        - is_active
        - location
        - title
        - type
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: seeker
    permission:
      columns:
        - company_id
        - created_at
        - description
        - id
        - is_active
        - location
        - title
        - type
        - updated_at
      filter:
        is_active:
          _eq: true
  - role: user
    permission:
      columns:
        - created_at
        - description
        - id
        - location
        - title
        - type
        - updated_at
      filter:
        is_active:
          _eq: true
update_permissions:
  - role: employer
    permission:
      columns:
        - description
        - location
        - title
        - type
      filter:
        company_id:
          _eq: X-Hasura-User-Id
      check:
        company_id:
          _eq: X-Hasura-User-Id
delete_permissions:
  - role: employer
    permission:
      filter:
        company_id:
          _eq: X-Hasura-User-Id
event_triggers:
  - name: newJobPost
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: http://192.168.1.102:3000/api/allJobs
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
